import QRCode from 'react-native-qrcode-svg';
import { RNCamera } from 'react-native-camera';
import ApiService from './ApiService';
import EncryptionService from './EncryptionService';

export interface QRPaymentData {
  type: 'receive' | 'pay' | 'split';
  amount?: number;
  currency: string;
  recipient?: string;
  sender?: string;
  description?: string;
  expiresAt?: Date;
  splitParticipants?: string[];
}

export interface QRCodeData {
  qrData: string;
  qrImage: string;
  expiresAt: Date;
}

export interface ScannedQRData {
  type: string;
  amount?: number;
  recipient?: string;
  description?: string;
  valid: boolean;
}

class QRPaymentService {
  private activeQRCodes: Map<string, QRCodeData> = new Map();

  async generateReceiveQRCode(amount?: number, description?: string): Promise<QRCodeData> {
    const qrId = this.generateQRId();
    const expiresAt = new Date(Date.now() + 15 * 60 * 1000); // 15 minutes

    const paymentData: QRPaymentData = {
      type: 'receive',
      amount,
      currency: 'USD',
      description,
      expiresAt,
    };

    // Encrypt payment data
    const encryptedData = await EncryptionService.encrypt(JSON.stringify(paymentData));

    // Generate QR code data
    const qrData = JSON.stringify({
      v: 1, // version
      id: qrId,
      data: encryptedData,
    });

    // Store active QR code
    const qrCodeData: QRCodeData = {
      qrData,
      qrImage: '', // Will be generated by QRCode component
      expiresAt,
    };

    this.activeQRCodes.set(qrId, qrCodeData);

    // Register QR code with backend
    await ApiService.post('/qr-payments/register', {
      qrId,
      paymentData,
      expiresAt,
    });

    return qrCodeData;
  }

  async generatePayQRCode(recipient: string, amount: number, description?: string): Promise<QRCodeData> {
    const qrId = this.generateQRId();
    const expiresAt = new Date(Date.now() + 15 * 60 * 1000);

    const paymentData: QRPaymentData = {
      type: 'pay',
      amount,
      currency: 'USD',
      recipient,
      description,
      expiresAt,
    };

    const encryptedData = await EncryptionService.encrypt(JSON.stringify(paymentData));

    const qrData = JSON.stringify({
      v: 1,
      id: qrId,
      data: encryptedData,
    });

    const qrCodeData: QRCodeData = {
      qrData,
      qrImage: '',
      expiresAt,
    };

    this.activeQRCodes.set(qrId, qrCodeData);

    await ApiService.post('/qr-payments/register', {
      qrId,
      paymentData,
      expiresAt,
    });

    return qrCodeData;
  }

  async generateSplitBillQRCode(
    totalAmount: number,
    participants: string[],
    description?: string
  ): Promise<QRCodeData> {
    const qrId = this.generateQRId();
    const expiresAt = new Date(Date.now() + 30 * 60 * 1000); // 30 minutes for split bills

    const amountPerPerson = totalAmount / participants.length;

    const paymentData: QRPaymentData = {
      type: 'split',
      amount: amountPerPerson,
      currency: 'USD',
      description,
      expiresAt,
      splitParticipants: participants,
    };

    const encryptedData = await EncryptionService.encrypt(JSON.stringify(paymentData));

    const qrData = JSON.stringify({
      v: 1,
      id: qrId,
      data: encryptedData,
    });

    const qrCodeData: QRCodeData = {
      qrData,
      qrImage: '',
      expiresAt,
    };

    this.activeQRCodes.set(qrId, qrCodeData);

    await ApiService.post('/qr-payments/register', {
      qrId,
      paymentData,
      expiresAt,
    });

    return qrCodeData;
  }

  async scanQRCode(qrData: string): Promise<ScannedQRData> {
    try {
      const parsed = JSON.parse(qrData);

      if (parsed.v !== 1) {
        throw new Error('Unsupported QR code version');
      }

      // Decrypt payment data
      const decryptedData = await EncryptionService.decrypt(parsed.data);
      const paymentData: QRPaymentData = JSON.parse(decryptedData);

      // Check expiration
      if (paymentData.expiresAt && new Date(paymentData.expiresAt) < new Date()) {
        return {
          type: paymentData.type,
          valid: false,
        };
      }

      // Validate with backend
      const response = await ApiService.post('/qr-payments/validate', {
        qrId: parsed.id,
      });

      if (!response.data.valid) {
        return {
          type: paymentData.type,
          valid: false,
        };
      }

      return {
        type: paymentData.type,
        amount: paymentData.amount,
        recipient: paymentData.recipient,
        description: paymentData.description,
        valid: true,
      };
    } catch (error) {
      console.error('Error scanning QR code:', error);
      return {
        type: 'unknown',
        valid: false,
      };
    }
  }

  async processQRPayment(qrData: string): Promise<{ success: boolean; transactionId?: string }> {
    const scannedData = await this.scanQRCode(qrData);

    if (!scannedData.valid) {
      throw new Error('Invalid or expired QR code');
    }

    try {
      const response = await ApiService.post('/qr-payments/process', {
        qrData,
        amount: scannedData.amount,
        recipient: scannedData.recipient,
        description: scannedData.description,
      });

      return {
        success: true,
        transactionId: response.data.transactionId,
      };
    } catch (error) {
      console.error('Error processing QR payment:', error);
      return {
        success: false,
      };
    }
  }

  async generateMerchantQRCode(
    merchantId: string,
    amount?: number,
    description?: string
  ): Promise<QRCodeData> {
    const qrId = this.generateQRId();
    const expiresAt = new Date(Date.now() + 60 * 60 * 1000); // 1 hour for merchant QR

    const paymentData: QRPaymentData = {
      type: 'pay',
      amount,
      currency: 'USD',
      recipient: merchantId,
      description,
      expiresAt,
    };

    const encryptedData = await EncryptionService.encrypt(JSON.stringify(paymentData));

    const qrData = JSON.stringify({
      v: 1,
      id: qrId,
      data: encryptedData,
      merchant: true,
    });

    const qrCodeData: QRCodeData = {
      qrData,
      qrImage: '',
      expiresAt,
    };

    this.activeQRCodes.set(qrId, qrCodeData);

    await ApiService.post('/qr-payments/merchant/register', {
      qrId,
      merchantId,
      paymentData,
      expiresAt,
    });

    return qrCodeData;
  }

  async generateDynamicQRCode(baseAmount: number, allowCustomAmount: boolean = true): Promise<QRCodeData> {
    const qrId = this.generateQRId();
    const expiresAt = new Date(Date.now() + 24 * 60 * 60 * 1000); // 24 hours for dynamic QR

    const paymentData: QRPaymentData = {
      type: 'receive',
      amount: allowCustomAmount ? undefined : baseAmount,
      currency: 'USD',
      description: allowCustomAmount ? 'Custom amount' : `Fixed amount: $${baseAmount}`,
      expiresAt,
    };

    const encryptedData = await EncryptionService.encrypt(JSON.stringify(paymentData));

    const qrData = JSON.stringify({
      v: 1,
      id: qrId,
      data: encryptedData,
      dynamic: true,
      baseAmount,
      allowCustomAmount,
    });

    const qrCodeData: QRCodeData = {
      qrData,
      qrImage: '',
      expiresAt,
    };

    this.activeQRCodes.set(qrId, qrCodeData);

    await ApiService.post('/qr-payments/dynamic/register', {
      qrId,
      paymentData,
      baseAmount,
      allowCustomAmount,
      expiresAt,
    });

    return qrCodeData;
  }

  async revokeQRCode(qrId: string): Promise<void> {
    this.activeQRCodes.delete(qrId);

    await ApiService.post('/qr-payments/revoke', { qrId });
  }

  async getQRCodeStatus(qrId: string): Promise<{ active: boolean; used: boolean; expiresAt?: Date }> {
    try {
      const response = await ApiService.get(`/qr-payments/status/${qrId}`);
      return response.data;
    } catch (error) {
      return { active: false, used: false };
    }
  }

  async getQRPaymentHistory(limit: number = 50): Promise<any[]> {
    try {
      const response = await ApiService.get(`/qr-payments/history?limit=${limit}`);
      return response.data.payments;
    } catch (error) {
      console.error('Error fetching QR payment history:', error);
      return [];
    }
  }

  private generateQRId(): string {
    return `qr_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
  }

  getActiveQRCodes(): QRCodeData[] {
    return Array.from(this.activeQRCodes.values());
  }

  cleanupExpiredQRCodes(): void {
    const now = new Date();
    for (const [qrId, qrData] of this.activeQRCodes.entries()) {
      if (qrData.expiresAt < now) {
        this.activeQRCodes.delete(qrId);
      }
    }
  }
}

export default new QRPaymentService();

